- name: "Tail some logs from running Ursula"
  hosts: "{{ nucypher_hosts | default('cassandra') }}"
  remote_user: "{{default_user}}"
  gather_facts: no
  tasks:
    - name: Find my public ip
      uri:
        url: http://ifconfig.me/ip
        return_content: yes
      register: ip_response

    - name: "Ursula Status"
      become: yes
      uri:
        url: "https://{{ip_response.content}}:9151/status/?json=true"
        validate_certs: no
      register: status_data

    - name: print result
      debug:
        msg: "{{status_data}}"
