version: '3'

# USEAGE
# docker-compose run nucypher-circle-dev bash download_finnegans_wake.sh
# docker-compose run nucypher-circle-dev python finnegans-wake-demo.py 172.29.1.3:11500
services:
  nucypher-circle-dev:
    ports:
      - 11500
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    image: circle:nucypher
    container_name: nucypher-circle-dev
    working_dir: /code/examples/
    networks:
      nucypher_circle_net:
        ipv4_address: 172.29.1.0
  circleusula1:
    ports:
      - 11500
    image: circle:nucypher
    command: nucypher  ursula run --dev --federated-only --rest-host 172.29.1.1 --rest-port 11500 --lonely
    networks:
      nucypher_circle_net:
        ipv4_address: 172.29.1.1
    container_name: circleusula1
  circleusula2:
    ports:
      - 11500
    image: circle:nucypher
    depends_on:
      - circleusula1
    command: nucypher  ursula run --dev --federated-only --rest-host 172.29.1.2 --rest-port 11500 --teacher 172.29.1.1:11500
    networks:
      nucypher_circle_net:
        ipv4_address: 172.29.1.2
    container_name: circleusula2
  circleusula3:
    ports:
      - 11500
    image: circle:nucypher
    depends_on:
      - circleursula2
    command: nucypher  ursula run --dev --federated-only --rest-host 172.29.1.3 --rest-port 11500 --teacher 172.29.1.1:11500
    networks:
      nucypher_circle_net:
        ipv4_address: 172.29.1.3
    container_name: circleusula3
  circleusula4:
    ports:
      - 11500
    image: circle:nucypher
    depends_on:
      - circleusula3
    command: nucypher  ursula run --dev --federated-only --rest-host 172.29.1.4 --rest-port 11500 --teacher 172.29.1.1:11500
    networks:
      nucypher_circle_net:
        ipv4_address: 172.29.1.4
    container_name: circleusula4


networks:
  nucypher_circle_net:
    ipam:
      driver: default
      config:
      - subnet: 172.29.1.0/16
