all:
  children:
    nucypher:
      children:
        cassandra:
          children:
            digitalocean:
              vars:
                default_user: "root"
              hosts:
                192.168.1.1:
                  GETH_ACCOUNT: "/Users/macperson/Library/Ethereum/goerli/keystore/UTC--2020-01-21T02-15-18.405738000Z--02e8cbf55e781ad4ca331fe5274be93814d760d0"
                  NUCYPHER_WORKER_ADDRESS: "0x02e8cbf55E781AD4cA331fe5274Be93814D760D0"
                  NUCYPHER_STAKER_ADDRESS: "0xD9b6B55b005f1B23b45a9a4aC9669deFac6dAd67"
            amazon:
              vars:
                ansible_ssh_private_key_file: ~/Downloads/damon-ansible-testing.pem
                default_user: "ubuntu"  # or root for digital ocean
              hosts:
                cassandra1.mystakednodez.com:
                  GETH_ACCOUNT: "/home/ubuntu/.ethereum/goerli/keystore/UTC--2020-01-21T02-15-33.342507000Z--d9e7ec6f9bb558c739cddbad5c38f170f1571077"
                  NUCYPHER_WORKER_ADDRESS: "0xd9e7eC6f9bB558c739CDdbAD5c38F170F1571077"
                  NUCYPHER_STAKER_ADDRESS: "0x4ffaEAe86c6A6f2C810F048877fbe1FBB2B27606"
          vars:
            network_name: cassandra
            geth_options: "--goerli"
            geth_dir: '/home/nucypher/geth/.ethereum/goerli/'
            NUCYPHER_KEYRING_PASSWORD: xxxxxxxxxxxxxxxxxxxxxxxpanda
            NUCYPHER_WORKER_ETH_PASSWORD: yyyyyyyyyyyyyyyyyyyystainpants
