- name: "Setup Remote Worker"
  hosts: "{{ nucypher_hosts | default('cassandra') }}"
  remote_user: "{{default_user}}"

- import_playbook: include/setup_user.yml
- import_playbook: include/setup_docker.yml
- import_playbook: include/init_worker.yml
- import_playbook: include/run_geth.yml
- import_playbook: include/init_ursula.yml
- import_playbook: include/run_ursula.yml
- import_playbook: include/check_running_ursula.yml