version: 2
jobs:
    build:
        working_directory: ~/nucypher-build
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - run:
                name: Pipenv installation
                command: |
                    pip install pipenv --upgrade
                    pipenv install --dev --three
            - run:
                name: Solc installation
                command: |
                    wget https://github.com/solidity/releases/download/v0.4.24/solc-static-linux -O "$(pipenv --venv)/bin/solc"
                    chmod +x "$(pipenv --venv)/bin/solc"
            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
                paths:
                    - "$(pipenv --venv)"
